# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Так себе программист"
logo: "/assets/images/logo.jpg"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
locale: "ru-RU"
lang: "ru"
date_format: "%d.%m.%Y"
time_format: "%H:%M"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _includes/head/custom.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  # name   : "Александр Троценко"
  # avatar : "/assets/images/bio-photo.jpg"
  bio    : "Признание - первый шаг на пути от \"так себе\" вчера к \"немного лучше\" сегодня."
  links:
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/mediocre_developer"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/@mediocredevelop?si=fh7IdFk_OsBR6gAb"
    - label: "ВКонтакте"
      icon: "fab fa-fw fa-vk"
      url: "https://vk.com/mediocredeveloper"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/trots"

footer:
  links:
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/mediocre_developer"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/@mediocredevelop?si=fh7IdFk_OsBR6gAb"
    - label: "ВКонтакте"
      icon: "fab fa-fw fa-vk"
      url: "https://vk.com/mediocredeveloper"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/trots"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      show_teaser: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
